//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRESHLyricMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FRESHLyricMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2022 Squidhouse Software (and open source contributors).
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string About_Framework {
            get {
                return ResourceManager.GetString("About_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under the MIT license.
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        public static string About_OperatingSystem {
            get {
                return ResourceManager.GetString("About_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRESHLyricMaker on the interwebs.
        /// </summary>
        public static string About_ProjectWebsite {
            get {
                return ResourceManager.GetString("About_ProjectWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Stream.
        /// </summary>
        public static string About_ReleaseStream {
            get {
                return ResourceManager.GetString("About_ReleaseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string About_ReportIssue {
            get {
                return ResourceManager.GetString("About_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View source code.
        /// </summary>
        public static string About_SourceCode {
            get {
                return ResourceManager.GetString("About_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using FRESHLyricMaker ❤.
        /// </summary>
        public static string About_Thankyou {
            get {
                return ResourceManager.GetString("About_Thankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a translation.
        /// </summary>
        public static string AddTranslation {
            get {
                return ResourceManager.GetString("AddTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back 5 seconds.
        /// </summary>
        public static string BackFiveSec {
            get {
                return ResourceManager.GetString("BackFiveSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced LRC is not supported yet :(.
        /// </summary>
        public static string EnhancedLRC_NotSupported {
            get {
                return ResourceManager.GetString("EnhancedLRC_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced LRC (word by word highlighting).
        /// </summary>
        public static string Export_EnhancedLRC {
            get {
                return ResourceManager.GetString("Export_EnhancedLRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires a special reader.
        /// </summary>
        public static string Export_EnhancedLRC_Hint {
            get {
                return ResourceManager.GetString("Export_EnhancedLRC_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Export_Format {
            get {
                return ResourceManager.GetString("Export_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRC Options.
        /// </summary>
        public static string Export_LRCOptions {
            get {
                return ResourceManager.GetString("Export_LRCOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling these might improve compatibility with certain readers.
        /// </summary>
        public static string Export_LRCOptions_HintOne {
            get {
                return ResourceManager.GetString("Export_LRCOptions_HintOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t enable them if you aren&apos;t having problems.
        /// </summary>
        public static string Export_LRCOptions_HintTwo {
            get {
                return ResourceManager.GetString("Export_LRCOptions_HintTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2 digits of precision.
        /// </summary>
        public static string Export_LRCOptions_TwoDigitPrecision {
            get {
                return ResourceManager.GetString("Export_LRCOptions_TwoDigitPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t include metadata headers.
        /// </summary>
        public static string Export_LRCOptions_WithoutMetadata {
            get {
                return ResourceManager.GetString("Export_LRCOptions_WithoutMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain LRC.
        /// </summary>
        public static string Export_PlainLRC {
            get {
                return ResourceManager.GetString("Export_PlainLRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most compatible.
        /// </summary>
        public static string Export_PlainLRC_Hint {
            get {
                return ResourceManager.GetString("Export_PlainLRC_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With translations.
        /// </summary>
        public static string Export_WithTranslations {
            get {
                return ResourceManager.GetString("Export_WithTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations only displays in compatible readers, readable (without translations) by most LRC readers.
        /// </summary>
        public static string Export_WithTranslations_Hint {
            get {
                return ResourceManager.GetString("Export_WithTranslations_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export!.
        /// </summary>
        public static string ExportEnthusiastically {
            get {
                return ResourceManager.GetString("ExportEnthusiastically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 5 seconds.
        /// </summary>
        public static string ForwardFiveSec {
            get {
                return ResourceManager.GetString("ForwardFiveSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Language.
        /// </summary>
        public static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} translation doesn&apos;t line up with the source.
        /// </summary>
        public static string InvalidTranslation {
            get {
                return ResourceManager.GetString("InvalidTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import _Audio.
        /// </summary>
        public static string Menu_File_Audio {
            get {
                return ResourceManager.GetString("Menu_File_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import _LRC File.
        /// </summary>
        public static string Menu_File_LRC {
            get {
                return ResourceManager.GetString("Menu_File_LRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About FRESHLyricMaker....
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help....
        /// </summary>
        public static string Menu_Help_OpenHelp {
            get {
                return ResourceManager.GetString("Menu_Help_OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string Menu_Options_Language {
            get {
                return ResourceManager.GetString("Menu_Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automatic.
        /// </summary>
        public static string Menu_Options_Language_Automatic {
            get {
                return ResourceManager.GetString("Menu_Options_Language_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Theme.
        /// </summary>
        public static string Menu_Options_Theme {
            get {
                return ResourceManager.GetString("Menu_Options_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark.
        /// </summary>
        public static string Menu_Options_Theme_Dark {
            get {
                return ResourceManager.GetString("Menu_Options_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Light.
        /// </summary>
        public static string Menu_Options_Theme_Light {
            get {
                return ResourceManager.GetString("Menu_Options_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Volume.
        /// </summary>
        public static string Menu_Options_Volume {
            get {
                return ResourceManager.GetString("Menu_Options_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next line.
        /// </summary>
        public static string NextLine {
            get {
                return ResourceManager.GetString("NextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next word.
        /// </summary>
        public static string NextWord {
            get {
                return ResourceManager.GetString("NextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous line.
        /// </summary>
        public static string PreviousLine {
            get {
                return ResourceManager.GetString("PreviousLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous word.
        /// </summary>
        public static string PreviousWord {
            get {
                return ResourceManager.GetString("PreviousWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Language.
        /// </summary>
        public static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start synchronizing, import an audio file using the File menu..
        /// </summary>
        public static string Synchronize_ImportHint {
            get {
                return ResourceManager.GetString("Synchronize_ImportHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp line.
        /// </summary>
        public static string TimestampLine {
            get {
                return ResourceManager.GetString("TimestampLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp word.
        /// </summary>
        public static string TimestampWord {
            get {
                return ResourceManager.GetString("TimestampWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure this matches line by line with the source language or you will be disappointed by the results.
        /// </summary>
        public static string TranslationHint {
            get {
                return ResourceManager.GetString("TranslationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word by word mode.
        /// </summary>
        public static string WordByWordMode {
            get {
                return ResourceManager.GetString("WordByWordMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
